#!/bin/bash

pull="$1";

show_git_timesheet () {

    local base_dir=$1;
	local tidy=$2;

    for repo in $(find $base_dir -maxdepth 3 -type d -name .git 2>/dev/null | grep -v old_code); do
        dir=${repo%.git}
        repo=$(expr "$repo" : '.*/\(.*\)/')
        cd $dir;
		if [ "$pull" == "pull" ]; then
			git pull
		fi
		count=$(git status -sb | wc -l)
		ahead=$(git status -sb | head -n1 | grep ahead)
		if [ "$count" -gt "1" -o "$ahead" != "" ]; then
			echo --- $repo ----;
			git status -sb
		fi
		if [ "$tidy" == "tidy" ]; then
			git-tidy-up
		fi
    done;
}

tidy=$1
show_git_timesheet '/Users/leejohnson/working/' $tidy;
