#!/bin/bash

function usage () {
    printf "Usage: %s: <directory>" $(basename $0) >&2
}

function blame_dir () {

    dir=$1

    for file in $(ls $dir)
    do
        blame=$(git log \
            -1 \
            --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' \
            --abbrev-commit \
            --date=relative \
            $dir/$file)
        echo $file - $blame
    done
}

if [ "$1" == "" ]; then
    usage
    exit 2
fi

blame_dir "$1"
