#!/bin/bash

week="$1";
args="$@";

show_git_timesheet () {

    local base_dir=$1;

    for repo in $(find $base_dir -maxdepth 4 -type d -name .git 2>/dev/null | grep -v old_code); do
        dir=${repo%.git}
        repo=$(expr "$repo" : '.*/\(.*\)/')
        cd $dir;
        if [ "$week" == "week" ]; then
			args=$(echo $args | sed 's/week//');
            work=$(git timesheetweek $args)
        elif [ "$week" == "we" ]; then
			args=$(echo $args | sed 's/we//');
            work=$(git timesheetwe $args)
        else
            work="$(git timesheet)"
        fi
		if [ "$work" != "" ]; then
			echo "";
	        echo --- $repo ----;
			echo "$work"
		fi
    done;
}

show_git_timesheet "$HOME/working/";
