#!/bin/bash

week=$1

show_git_timesheet () {

    local base_dir=$1;

    for repo in $(find $base_dir -maxdepth 3 -type d -name .git 2>/dev/null); do
        dir=${repo%.git}
        repo=$(expr "$repo" : '.*/\(.*\)/')
        cd $dir;
        echo --- $repo ----;
        if [ "$week" == "week" ]; then
            git timesheetweek;
        else
            git timesheet;
        fi
    done;
}

show_git_timesheet '/Users/leejohnson/working/';
