#!/bin/bash

week="$1";
args="$@";

show_git_timesheet () {

    local base_dir=$1;

    for repo in $(find $base_dir -maxdepth 3 -type d -name .git 2>/dev/null | grep -v old_code); do
        dir=${repo%.git}
        repo=$(expr "$repo" : '.*/\(.*\)/')
        cd $dir;
        echo --- $repo ----;
        if [ "$week" == "week" ]; then
			args=$(echo $args | sed 's/week//');
            git timesheetweek $args
        elif [ "$week" == "we" ]; then
			args=$(echo $args | sed 's/we//');
            git timesheetwe $args
        else
            git timesheet $args
        fi
    done;
}

show_git_timesheet '/Users/leejohnson/working/';
